artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/uc?id=1K-V250xDFAOsEDN0QLKtYblrAEHE6Ski
  local_data_file: artifacts/data_ingestion/data_main.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_ingestion/winequality-red.csv
  validation_status_path: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv
  train_path: artifacts/data_transformation/train.csv
  test_path: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_path: artifacts/data_transformation/train.csv
  test_path: artifacts/data_transformation/test.csv
  model_name: artifacts/model_trainer/model.joblib
